name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
version: 0.11.7
homepage: https://github.com/cloudwebrtc/flutter-webrtc
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.22.0'

dependencies:
  collection: ^1.17.0
  dart_webrtc: ^1.4.9
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  webrtc_interface:
    git:
      url: git@github.com:Hamdal/webrtc-interface.git
      ref: feat/additional-videoviewobject-fit

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^4.0.0
  pedantic: ^1.11.1
  test: any

dependency_overrides:
  webrtc_interface:
    git:
      url: git@github.com:Hamdal/webrtc-interface.git
      ref: feat/additional-videoviewobject-fit

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
      linux:
        pluginClass: FlutterWebRTCPlugin
      elinux:
        pluginClass: FlutterWebRTCPlugin